### ISSUE TITLE
Bug[high]: Users may be blocked from adding owners.

### ISSUE THREAD

**Issue by pegahcarter** [coinbase/smart-wallet#11]
## Summary
A user may unintentionally get blocked from adding new owners.

## Description
When adding an owner, the `nextOwnerIndex` is incremented.  However, when removing an owner, `nextOwnerIndex` remains the same.  Once 255 owners have been added, a user is unable to add owners because of the uint8 overflow within `_addOwner()`.  This limitation will still exist even after owners have been removed, as `nextOwnerIndex` will still be 255.

**Comment by pegahcarter** [comment]
Nevermind.  Looks like this was resolved with #9 .

**Comment by wilsoncusack** [comment]
Thanks @pegahcarter, this is documented behavior https://github.com/coinbase/smart-wallet/blob/main/src/MultiOwnable.sol#L6  

https://github.com/coinbase/smart-wallet/blob/main/src/MultiOwnable.sol#L43-L51
