### ISSUE TITLE
bug: missing 0 checks

### ISSUE THREAD

**Issue by pegahcarter** [coinbase/smart-wallet#16]
We should add validations within `addOwnerAddress()` and `addOwnerPublicKey()` to require that the owner != 0.

**Comment by wilsoncusack** [comment]
Thanks, but we do not intend to add these kinds of checks. There are many erroneous addresses that could be passed and we cannot control for all of them.

**Comment by pegahcarter** [comment]
Just note that if owner 0 is added, it can never be removed.
