### ISSUE TITLE
Entrypoint contract reference for V0.7

### ISSUE THREAD

**Issue by kanthgithub** [coinbase/smart-wallet#3]
## Background
[EntryPointContractAddress in SmartWallet](https://github.com/coinbase/smart-wallet/blob/main/src/CoinbaseSmartWallet.sol#L236-L238) is hardcoded to v0.6 version

## Question
How to manage this for V0.7? 
should this be made configurable or create another SmartWallet Contract file for V0.7 as UserOps Struct is updated in 0.7

**Comment by kanthgithub** [comment]
@wilsoncusack looking forward to contribute to codebase
please let me know if i can take up any issues

**Comment by wilsoncusack** [comment]
Hey @kanthgithub we are still considering whether we will support v0.7. Several things would have to change if we choose to do so. Closing this for now.
