### ISSUE TITLE
Passkey signatures failing for some hashes

### ISSUE THREAD

**Issue by jamesmccomish** [coinbase/smart-wallet#41]
I was running tests on a fork of the smart wallet and getting errors for some tests. 

I was following the same signing procedure as in this repo, and eventually found that the [signature malleability check](https://github.com/base-org/webauthn-sol/blob/01ab6f8c1897b2fc682deb4eb56532b69c8b4abd/src/WebAuthn.sol#L107) in WebAuthn-Sol was returning the error due to `s` being too large.

[This test](https://github.com/jamesmccomish/smart-wallet/blob/5a1e10251acfe974d3722eb81a8e28c8846079e1/test/CoinbaseSmartWallet/IsValidSignature.t.sol#L12) shows that for some hashes the values returned from vm.signP256 are causing the problem. I added a test `testValidateSignatureWithPasskeySignerWithSCheck` which passes when we take the compliment of `s`.

Is this something that should be handled by signP256? Maybe I have misunderstood what `webAuthn.messageHash` should be and that is causing the wrong signatures?

**Comment by wilsoncusack** [comment]
Hey, thanks for this! [Here](https://github.com/base-org/webauthn-sol/blob/main/test/Webauthn.fuzz.t.sol#L71-L73) is how you can normalize `s` values control for this. We'd expect clients to do this normalization.

**Comment by jamesmccomish** [comment]
Ah thanks, yea I see it is expected then. Will take it into account from here
