### ISSUE TITLE
Smart contract consultation

### ISSUE THREAD

**Issue by ujkk858** [coinbase/smart-wallet#49]
I have a bytecode of a contract transaction on Coinbase, and I can find the contract on Ethereum, but I cannot find the corresponding ABI information for the contract. As a result, I am unable to decode the transaction content. Can you provide the ABI information, or does Coinbase have a corresponding API that can be called for this purpose?

Smart contract address : 0xa9d1e08c7793af67e9d92fe308d5697fb81d3e43

Transaction bytecode:
0xca350aa60000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000003d090000000000000000000000000000000000000000000000000000000000000000f000000000000000000000000
a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000bb49af4efe13a71306f38614d7ee9b96a3143410000000000000000000000000000000000000000000000000000000000542a8bc000000000000000000000000
a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000aefde148d87b2ecedb2a7fdef8ddcea4fa96e8ad000000000000000000000000000000000000000000000000000000000a3248eb000000000000000000000000
a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000db946e8437fe68038d238c5dc3f2e887a81b350c000000000000000000000000000000000000000000000000000000001da28470000000000000000000000000
a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000002ab40224a25f1f42e3609c682cd3e3fce62a66ad000000000000000000000000000000000000000000000000000000012a05f200000000000000000000000000
a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000bf59510774e2c64b12b067c7cf35fa5a1c594311000000000000000000000000000000000000000000000000000000012eb50d4c000000000000000000000000
dac17f958d2ee523a2206206994597c13d831ec700000000000000000000000023866a9d84638b951e494b7f91a953d0a8e58988000000000000000000000000000000000000000000000000000000000efdbcf0000000000000000000000000
dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000d44efcd7dbffb24ec84e5477e00c7de9be0424eb000000000000000000000000000000000000000000000000000000001d769cb7000000000000000000000000
dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000002d5409ded062030bd6abe1e2096c826786994253000000000000000000000000000000000000000000000000000000008695e71a000000000000000000000000
dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000004ecc9f6724008cb9febe894f73ddb70b32c540ce000000000000000000000000000000000000000000000000000000008821b5d2000000000000000000000000
dac17f958d2ee523a2206206994597c13d831ec700000000000000000000000050a8646633e17102431a2cd4b434bb6b3f6dc90a00000000000000000000000000000000000000000000000000000003766d4e9b000000000000000000000000
464ebe77c293e473b48cfe96ddcf88fcf7bfdac0000000000000000000000000d6eb1293ad25dbfa297c4f36bc84ed6f441077b9000000000000000000000000000000000000000000000068158dfd0e42e91c00000000000000000000000000
9e46a38f5daabe8683e10793b06749eef7d733d100000000000000000000000095ef9a234f8415a2de36b70b477ee444777ccba2000000000000000000000000000000000000000000003a68d1ad103e542e9400000000000000000000000000
9e46a38f5daabe8683e10793b06749eef7d733d1000000000000000000000000f14af9cc75a483b27ddbb5e1a95f0374a6b4b8e200000000000000000000000000000000000000000000463fc2ab8f11d56a9400000000000000000000000000
95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce000000000000000000000000b74d68ddd7454908d853592fa6185d8435017caf000000000000000000000000000000000000000000005aeea12bde87d3a17c00000000000000000000000000
514910771af9ca656af840dff83e8264ecf986ca0000000000000000000000001850c9b73458350df56ab62a2cb91fabbd951b3c0000000000000000000000000000000000000000000000011a45208ed9c93400

**Comment by wilsoncusack** [comment]
@ujkk858 closing for now. Let me know if there is any remaining issue.
