### ISSUE TITLE
No CI

### ISSUE THREAD

**Issue by pegahcarter** [coinbase/smart-wallet#5]
I propose adding a CI pipeline so that any local work of the repo can be guaranteed to build.  The current commit ([5bad101](https://github.com/coinbase/smart-wallet/commit/5bad101604a6cd8356434faa016d608a8523396c)) breaks on build, slowing down development time for internal team and public contributors.

**Comment by pegahcarter** [comment]
For example, something like https://github.com/FraxFinance/frax-template makes development on new repositories super simple.  It also use pnpm, a faster alternative to .gitmodules, and supports all protocol-wide contract imports (a challenge when working across repos).

**Comment by wilsoncusack** [comment]
Thanks! We had some non-public deps that broke CI before launch but I have a branch with a workflow for tests and lint. Will put up

**Comment by pegahcarter** [comment]
If you switch from `.gitmodules` to `node_modules` you'll be able to depend on private deps.

**Comment by wilsoncusack** [comment]
Roger, not an issue anymore!
