### ISSUE TITLE
Opinion: can reduce arguments of `removeOwner()`

### ISSUE THREAD

**Issue by pegahcarter** [coinbase/smart-wallet#62]
From:
https://github.com/coinbase/smart-wallet/blob/adab965145cc7a6f938dd118295c6ae062672838/src/MultiOwnable.sol#L122

It seems a bit redundant to require the caller to pass in both the index *and* the bytes.  Perhaps two overloading methods would suffice, one for index only and one for the bytes?

**Comment by wilsoncusack** [comment]
Thanks! See https://github.com/coinbase/smart-wallet/pull/42
